on:
  push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Lint code
        run: |
          OUTPUT=$(python -m flake8 --max-line-length=100 src/ tests/)
          echo $OUTPUT
          echo "MESSAGE=$OUTPUT" >> $GITHUB_ENV
          echo $env.MESSAGE
      - name: Post result to PR
        uses: mshick/add-pr-comment@v1
        with:
          message: ${{ env.MESSAGE }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
      - name : Format Check
        run: python -m black --check src/ tests/
